version: '3'
services:

  frontend:
    build:
      context: ./public
      - "3000:3000"
    depends_on:
      - backend
      
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://admin:G6WUuzoXrn8wFsgy@chat.qpo6lyz.mongodb.net/?retryWrites=true&w=majority 
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
