version: '3'
services:

  frontend:
    build:
      context: ./public
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://admin:ChatApp23@freecluster.ave7m16.mongodb.net/?retryWrites=true&w=majority
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend