version: '3'
services:

  frontend:
    build:
      context: ./public
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
