version: '3.8'
services:
  server:
    image: server
    build:
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production

  public:
    image: public
    build:
      dockerfile: Dockerfile
    container_name: public
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/my_project:/var/www/project1

  nodeapp:
    container_name: node
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: server/.env
    ports:
      - "4500:4500"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge