name: Run Tests on Staging Branch

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm i
        working-directory: server

      - name: Run tests
        run: npm test
        working-directory: server
