name: Test

on:
  push:
    branches:
      - staging

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18-alpine
        uses: actions/setup-node@v3
        with:
          node-version: 18-alpine

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run tests
        run: npm run test
        working-directory: ./server
