name: Build and Test

on:
  pull_request:
  push:
    branches:
      - staging

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Change Working Directory
        working-directory: ./server

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
